启用ai入群欢迎: true
通用入群欢迎: '欢迎。'
自定义入群欢迎:  #需要关闭ai入群欢迎
  - 699455550: '欢迎'
自动退群: false
自动退出少于此人数的群: 1
自动退出多于此人数的群: 10000
BullshitMsgBlocker:  #防止群友自言自语
  enable: false
  blockList:  #管理的群列表，列表中的群才会被检测
    - 913122269
    - 1050663831
  消息缓存池大小: 5 #缓存最近{n}条消息。建议根据实际需要调整。
  每人最大发言数量: 5 #最近{缓存池}消息中，当单个用户发言达到{n}条时，触发禁言
  禁言时长: 180 #禁言{禁言时长}秒
  嘲讽: "检测到群友自言自语，已禁言180秒。"