today_wife:
  api:
  - 'https://sese.iw233.top/iapi.php?sort=random'
  - 'https://moe.jitsu.top/api'
  - 'https://api.seaya.link/wap'
  header: 'https://weibo.com/'          #知道的自己改，不知道的不要动
  wifePrefix: '/'                       #透群友的指令前缀
  今日萝莉: True
  今日老公: True
  今日老婆: True
  复读开关: True
  签🦌撤回: True
  透群友撤回: True
  仅热门群友: False #只会透到最近发言较多的群友
  is_at: True #今日群友/管理/群主 是否艾特其本人
emojimix:         #emoji合成相关
  enable: True    #是否开启emoji合成